# -*- coding: utf-8 -*-
"""CVRP Heuristic Solver.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kKID1JLE2BqLYYMUsJLEk3q4qiWnZeD0
"""



# CVRP HEURISTIC SOLVER
# A-n32-k5
# Sweep, Clarke & Wright, Nearest Neighbour

from google.colab import files
import math
import pandas as pd
import matplotlib.pyplot as plt


# 1.Upload and read .vrp file


uploaded = files.upload()
filename = list(uploaded.keys())[0]

coordinates = {}
demands = {}

reading_coords = False
reading_demands = False
capacity = None
depot = 1

with open(filename, "r") as file:
    for line in file:
        line = line.strip()

        if line.startswith("CAPACITY"):
            capacity = int(line.split(":")[1].strip())

        elif line == "NODE_COORD_SECTION":
            reading_coords = True
            reading_demands = False
            continue

        elif line == "DEMAND_SECTION":
            reading_coords = False
            reading_demands = True
            continue

        elif line == "DEPOT_SECTION":
            reading_coords = False
            reading_demands = False
            continue

        elif line == "EOF":
            break

        elif reading_coords:
            parts = line.split()
            node = int(parts[0])
            x = int(parts[1])
            y = int(parts[2])
            coordinates[node] = (x, y)

        elif reading_demands:
            parts = line.split()
            node = int(parts[0])
            demand = int(parts[1])
            demands[node] = demand

nodes = sorted(coordinates.keys())
customers = [n for n in nodes if n != depot]

print("Nodes loaded:", len(nodes))
print("Customers loaded:", len(customers))
print("Vehicle capacity:", capacity)


# 2. DISTANCE MATRIX


def euclidean_distance(i, j):
    x1, y1 = coordinates[i]
    x2, y2 = coordinates[j]
    return round(math.sqrt((x1 - x2)**2 + (y1 - y2)**2))

distance = {
    i: {j: euclidean_distance(i, j) for j in nodes}
    for i in nodes
}


# 3. helper functions


def route_cost(route):
    return sum(distance[route[i]][route[i + 1]] for i in range(len(route) - 1))

def route_load(route):
    return sum(demands[n] for n in route if n != depot)

def total_cost(routes):
    return sum(route_cost(r) for r in routes)

def two_opt(route):
    best = route[:]
    improved = True

    while improved:
        improved = False
        best_cost = route_cost(best)

        for i in range(1, len(best) - 2):
            for j in range(i + 1, len(best) - 1):
                if j - i == 1:
                    continue

                candidate = best[:]
                candidate[i:j] = reversed(candidate[i:j])
                candidate_cost = route_cost(candidate)

                if candidate_cost < best_cost:
                    best = candidate
                    improved = True
                    break

            if improved:
                break

    return best


# 4. SWEEP HEURISTIC
# Multi-start Sweep + 2-opt


def solve_sweep():
    dx, dy = coordinates[depot]

    angle_list = []

    for c in customers:
        x, y = coordinates[c]
        angle = math.atan2(y - dy, x - dx)

        if angle < 0:
            angle += 2 * math.pi

        angle_list.append((c, angle))

    angle_list.sort(key=lambda x: x[1])

    def build_sweep_routes(start_index):
        ordered = angle_list[start_index:] + angle_list[:start_index]
        ordered_customers = [c for c, a in ordered]

        routes = []
        current_route = [depot]
        current_load = 0

        for c in ordered_customers:
            demand = demands[c]

            if current_load + demand <= capacity:
                current_route.append(c)
                current_load += demand
            else:
                current_route.append(depot)
                routes.append(current_route)

                current_route = [depot, c]
                current_load = demand

        current_route.append(depot)
        routes.append(current_route)

        return routes

    best_routes = None
    best_total = float("inf")

    for start in range(len(angle_list)):
        routes = build_sweep_routes(start)
        improved_routes = [two_opt(r) for r in routes]
        cost = total_cost(improved_routes)

        if cost < best_total:
            best_total = cost
            best_routes = improved_routes

    return best_routes, best_total


# 5. CLARKE & WRIGHT SAVINGS HEURISTIC
# Parallel Savings + 2-opt


def find_route_containing(routes, customer):
    for idx, route in enumerate(routes):
        if customer in route:
            return idx
    return None

def solve_clarke_wright():
    routes = [[depot, c, depot] for c in customers]

    savings = []

    for i in customers:
        for j in customers:
            if i < j:
                s = distance[depot][i] + distance[depot][j] - distance[i][j]
                savings.append((i, j, s))

    savings.sort(key=lambda x: x[2], reverse=True)

    print("\n========== TOP 10 SAVINGS ==========")
    for item in savings[:10]:
        print(item)

    for i, j, s in savings:
        ri = find_route_containing(routes, i)
        rj = find_route_containing(routes, j)

        if ri is None or rj is None or ri == rj:
            continue

        route_i = routes[ri]
        route_j = routes[rj]

        i_at_start = route_i[1] == i
        i_at_end = route_i[-2] == i
        j_at_start = route_j[1] == j
        j_at_end = route_j[-2] == j

        if not ((i_at_start or i_at_end) and (j_at_start or j_at_end)):
            continue

        combined_load = route_load(route_i) + route_load(route_j)

        if combined_load > capacity:
            continue

        merged_route = None

        if i_at_end and j_at_start:
            merged_route = route_i[:-1] + route_j[1:]

        elif i_at_start and j_at_end:
            merged_route = route_j[:-1] + route_i[1:]

        elif i_at_start and j_at_start:
            merged_route = [depot] + route_i[1:-1][::-1] + route_j[1:]

        elif i_at_end and j_at_end:
            merged_route = route_i[:-1] + route_j[1:-1][::-1] + [depot]

        if merged_route is not None:
            for idx in sorted([ri, rj], reverse=True):
                del routes[idx]

            routes.append(merged_route)

    routes = [two_opt(r) for r in routes]
    return routes, total_cost(routes)


# 6.NEAREST NEIGHBOUR HEURISTIC
# Multi-start Nearest Neighbour + 2-opt


def build_nearest_neighbour_routes(first_customer=None):
    unvisited = set(customers)
    routes = []

    while unvisited:
        route = [depot]
        load = 0
        current = depot

        if first_customer is not None and first_customer in unvisited:
            route.append(first_customer)
            load += demands[first_customer]
            unvisited.remove(first_customer)
            current = first_customer

        while True:
            feasible = [
                c for c in unvisited
                if load + demands[c] <= capacity
            ]

            if not feasible:
                break

            next_customer = min(
                feasible,
                key=lambda c: distance[current][c]
            )

            route.append(next_customer)
            load += demands[next_customer]
            unvisited.remove(next_customer)
            current = next_customer

        route.append(depot)
        routes.append(route)

        first_customer = None

    return routes

def solve_nearest_neighbour():
    best_routes = None
    best_total = float("inf")

    candidate_routes = build_nearest_neighbour_routes()
    candidate_routes = [two_opt(r) for r in candidate_routes]
    candidate_total = total_cost(candidate_routes)

    best_routes = candidate_routes
    best_total = candidate_total

    for start_customer in customers:
        candidate_routes = build_nearest_neighbour_routes(first_customer=start_customer)
        candidate_routes = [two_opt(r) for r in candidate_routes]
        candidate_total = total_cost(candidate_routes)

        if candidate_total < best_total:
            best_total = candidate_total
            best_routes = candidate_routes

    return best_routes, best_total


# 7. Print results


def print_solution(name, routes, total):
    best_known = 784
    gap = ((total - best_known) / best_known) * 100

    print("\n" + "=" * 50)
    print(name)
    print("=" * 50)

    for idx, r in enumerate(routes, start=1):
        print(f"\nVehicle {idx}")
        print("Route:", r)
        print("Load:", route_load(r))
        print("Distance:", route_cost(r))

    print("\nNumber of routes:", len(routes))
    print("Total distance:", total)
    print("Best known solution:", best_known)
    print(f"Gap: {gap:.2f}%")


sweep_routes, sweep_total = solve_sweep()
cw_routes, cw_total = solve_clarke_wright()
nn_routes, nn_total = solve_nearest_neighbour()


print_solution("IMPROVED SWEEP HEURISTIC", sweep_routes, sweep_total)
print_solution("CLARKE & WRIGHT SAVINGS HEURISTIC", cw_routes, cw_total)
print_solution("IMPROVED NEAREST NEIGHBOUR HEURISTIC", nn_routes, nn_total)


# 8. COMPARISON


comparison = pd.DataFrame({
    "Method": [
        "Sweep",
        "Clarke & Wright",
        "Nearest Neighbour"
    ],
    "Distance": [
        sweep_total,
        cw_total,
        nn_total
    ],
    "Gap (%)": [
        ((sweep_total - 784) / 784) * 100,
        ((cw_total - 784) / 784) * 100,
        ((nn_total - 784) / 784) * 100
    ]
})

comparison

# ROUTE VISUALIZATION FUNCTION


def plot_routes(routes, title):
    plt.figure(figsize=(10, 10))

    for r in routes:
        xs = [coordinates[n][0] for n in r]
        ys = [coordinates[n][1] for n in r]
        plt.plot(xs, ys, marker="o", linewidth=2)

    dx, dy = coordinates[depot]
    plt.scatter(dx, dy, s=300, marker="s", color="black", label="Depot")

    for n, (x, y) in coordinates.items():
        plt.text(x + 1, y + 1, str(n), fontsize=8)

    plt.title(title)
    plt.xlabel("X Coordinate")
    plt.ylabel("Y Coordinate")
    plt.grid(True)
    plt.legend()
    plt.tight_layout()
    plt.show()


# Plot each heuristic route solution
plot_routes(sweep_routes, "Sweep Heuristic Solution - A-n32-k5")
plot_routes(cw_routes, "Clarke & Wright Savings Heuristic Solution - A-n32-k5")
plot_routes(nn_routes, "Nearest Neighbour Solution - A-n32-k5")

import matplotlib.pyplot as plt

plt.figure(figsize=(9, 8))

# Plot customers
for node, (x, y) in coordinates.items():
    if node == depot:
        plt.scatter(x, y, marker="s", s=220, label="Depot")
        plt.text(x + 1, y + 1, f"Depot ({node})", fontsize=9)
    else:
        plt.scatter(x, y, s=45)
        plt.text(x + 1, y + 1, str(node), fontsize=8)

plt.title("Customer Distribution Map (A-n32-k5)")
plt.xlabel("X Coordinate")
plt.ylabel("Y Coordinate")
plt.grid(True)
plt.legend()
plt.tight_layout()

plt.savefig("customer_distribution_map.png", dpi=300)
plt.show()

import pandas as pd
import matplotlib.pyplot as plt


distance_matrix_df = pd.DataFrame(distance)
distance_matrix_df = distance_matrix_df.loc[nodes, nodes]

plt.figure(figsize=(10, 8))

plt.imshow(distance_matrix_df, aspect="auto")
plt.colorbar(label="Distance")

plt.title("Distance Matrix Heatmap (A-n32-k5)")
plt.xlabel("Destination Node")
plt.ylabel("Origin Node")

plt.xticks(range(len(nodes)), nodes, rotation=90, fontsize=7)
plt.yticks(range(len(nodes)), nodes, fontsize=7)

plt.tight_layout()

plt.savefig("distance_matrix_heatmap.png", dpi=300)
plt.show()